export const courses = [
  {
    id: 1,
    name: "Web Development Bootcamp",
    description: "Learn web development from scratch.",
    tutor: "John Doe",
    price: "$199",
    category: "web-development",
  },
  {
    id: 2,
    name: "Data Science with Python",
    description: "Master data science and machine learning.",
    tutor: "Jane Smith",
    price: "$299",
    category: "data-science",
  },
  {
    id: 3,
    name: "UI/UX Design",
    description: "Learn the fundamentals of design.",
    tutor: "Alice Johnson",
    price: "$149",
    category: "design",
  },
  {
    id: 4,
    name: "Digital Marketing Essentials",
    description: "Understand the basics of digital marketing strategies.",
    tutor: "Michael Brown",
    price: "$199",
    category: "marketing",
  },
  {
    id: 5,
    name: "Mobile App Development",
    description: "Build apps for iOS and Android platforms.",
    tutor: "Emily Davis",
    price: "$299",
    category: "mobile-development",
  },
  {
    id: 6,
    name: "Machine Learning A-Z",
    description: "Become a master of machine learning with Python.",
    tutor: "Chris Green",
    price: "$399",
    category: "data-science",
  },
  {
    id: 7,
    name: "Full Stack Development",
    description: "Learn full-stack development using MERN stack.",
    tutor: "Sarah Wilson",
    price: "$249",
    category: "web-development",
  },
  {
    id: 8,
    name: "Introduction to Cybersecurity",
    description: "Understand the basics of cybersecurity.",
    tutor: "David Clark",
    price: "$199",
    category: "cybersecurity",
  },
  {
    id: 9,
    name: "Game Development with Unity",
    description: "Create stunning games using Unity engine.",
    tutor: "Laura Martinez",
    price: "$299",
    category: "game-development",
  },
  {
    id: 10,
    name: "Cloud Computing Fundamentals",
    description: "Learn about cloud computing and services.",
    tutor: "James Lee",
    price: "$199",
    category: "cloud-computing",
  },
  {
    id: 11,
    name: "Introduction to Blockchain",
    description: "Understand blockchain technology and its applications.",
    tutor: "Linda Taylor",
    price: "$249",
    category: "blockchain",
  },
  {
    id: 12,
    name: "Photography Basics",
    description: "Learn the basics of photography and editing.",
    tutor: "Robert Wilson",
    price: "$99",
    category: "photography",
  },
  {
    id: 13,
    name: "Public Speaking Masterclass",
    description: "Develop effective public speaking skills.",
    tutor: "Nancy Hall",
    price: "$149",
    category: "communication",
  },
  {
    id: 14,
    name: "Creative Writing Workshop",
    description: "Enhance your writing skills with creative techniques.",
    tutor: "William Allen",
    price: "$129",
    category: "writing",
  },
  {
    id: 15,
    name: "Excel for Beginners",
    description: "Master Excel with this beginner's course.",
    tutor: "Patricia Young",
    price: "$99",
    category: "business",
  },
];
